schema_admin_password = "wordpass"
# .streamlit/secrets.toml
schema_password = "wordpass"

authorized_users = [
    "user1@example.com",
    "user2@example.com"
]

authorized_admins = [
    "admin1@example.com",
    "admin2@example.com"
]